var res = {
    helloBG_png : "res/image/pic/loadBg.png",
    start_n_png : "res/image/pic/start_n.png",
    start_s_png : "res/image/pic/start_s.png",
    playBG_png : "res/image/pic/playBg.png",
    oper_png : "res/image/pic/oper.png",
    guard1_png : "res/image/pic/guard/guard1.png",
    guard1_plist : "res/image/pic/guard/guard1.plist",
    mobs1_plist : "res/image/pic/guard/mobs1.plist",
    mobs2_plist : "res/image/pic/guard/mobs2.plist",
    mobs3_plist : "res/image/pic/guard/mobs3.plist",
    mobs4_plist : "res/image/pic/guard/mobs4.plist",
    mobs5_plist : "res/image/pic/guard/mobs5.plist",
    mobs6_plist : "res/image/pic/guard/mobs6.plist",
};
var g_resources = [
    res.helloBG_png,
    res.start_n_png,
    res.start_s_png,
    res.playBG_png,
    res.oper_png,
    res.guard1_png,
    res.guard1_plist,
    res.mobs1_plist,
    res.mobs2_plist,
    res.mobs3_plist,
    res.mobs4_plist,
    res.mobs5_plist,
    res.mobs6_plist,
];